### ISSUE TITLE
Trying to repurpose to use public Purple Air sensors

### ISSUE THREAD

**Issue by danswett** [dclaar/purple_air#1]
Hey,

Trying to repurpose your code to do the same thing but pulling the JSON from the public Purple Air sensors. This means instead of an IP, you'll start with a full URL like this: https://www.purpleair.com/json?show=38607

Seems conceptually straightforward, but I'm having quite the time trying to debug it since it relies on libraries from the device and when I try to run it the device just... does nothing (or says "reupload file"). I'm rather new to working with hardware like this, so apologies for dumb questions, and i'm starting to try and wade through the forums but figured I'd ask here too.

Sorry if this is the wrong way to ask, or if you don't have time I'll keep poking away at it.

Came here via Steve Roth.

Thanks,
Dan

**Comment by dclaar** [comment]
I don't know if there's a better way to ask! But yeah, debug is tough. I'm mostly done with a pygames simulation to increase development velocity, but it's still not completely the same.

What are you using for your development cycle? I tried Visual Code Studio, but couldn't get the serial port monitoring to work, and VCS often dropped the connection altogether. It's useful for quick syntax checks though.

My workflow was generally to 
- Open a command window / shell.
- cd into purple_air.
- Fire up a rshell connection (pip install rshell; https://github.com/dhylands/rshell).
- Edit files.
- cp flash/apps/AQI.py /flash/apps/AQI.py  # in rshell
- repl   # in rshell
- Hold down the A button, press power, then go to apps, and start AQI from there.

Any errors show up in rshell.

- control-x to get out of repl.
- Fix the darn typo / bug.
- Lather, rinse, repeat.

I mean, I hate to admit it, it's a horrible workflow! But I haven't come up with a better one: That's why I took time out to put together the pygame simulator. (The M5Stack Core is easier to work with, because it has enough screen to actually show the errors, but it's more expensive, and the code is not really written to look good on it).

You will note that the JSON from the URL does not contain the AQI, only PM2.5. I have some code that does the conversion, based on code from Purple air in their FB group.

I'll try to get an update out this week. (Oh dear, I've committed myself now, haven't I?) :)

**Comment by danswett** [comment]
Thanks I’ll give this a go! I’ve never done any work with microcontrollers
like this so the flow is all new to me.

I’ve been using VScode thus far, and have found it fairly reliable with
transferring files and executing on the device, but on Windows so no easy
way to get to the shell as part of that. I’ve been closing the connection
and using Putty, but as I think you commented on the forums it’s really
cumbersome.

I got some code running that can pull sensor data from Purple’s API and
calc the AQI using python-AQI, but I’ve been struggling to refactor your
code to use it. Right now I can’t even get it to load (if I load a
different app first it will say “Upload Again” when I try to run), and of
course I can’t run it in Code because there’s no emulator.

Appreciate your response - so much to learn!

Dan

**Comment by dclaar** [comment]
I think that I should abstract out the device interface. Should be pretty
simple, and then I can add an abstraction for the web interface.

I'm never going to discourage anyone from working on microcontrollers,
because they are a whole lot of fun (I guess, depending on your definition
of fun! But for me, connecting code to the real world is rewarding). So
feel free to keep at it! But I should be able to support the web interface
pretty soon.

**Comment by dclaar** [comment]
I have just uploaded a version that works with both local and web-based purple air interfaces.

**Comment by danswett** [comment]
Thank you!
