### ISSUE TITLE
App freezes when changing UI

### ISSUE THREAD

**Issue by danswett** [dclaar/purple_air#2]
I assume I'm doing something wrong, but I've tried on two different M5StickC devices with the same result. As I log this I'm also trying to go through the code.

**Setup**:
Load app onto device using "copy_for_web.py"
1. Connect device to https://flow.m5stack.com
2. Switch to "</> Python" tab
3. Copy/paste code from "copy_for_web.py"
4. Replace "00000" with actual sensor ID
5. Press "Play" button and wait for device to show "DONE!"

**Repro**:
1. Boot device while holding button A
2. Change to App list and boot WebAQI.py
3. Wait for "Wifi connected"

**Actual**:
1. App boots and shows "n/a" with mode R, flashing heart icon, and marching ants
2. Press button A to change modes - marching ants pause and "R" flashes
3. Press button B once - marching ants pause, "R" changes to "N" and screen shows AQI value with colored background
4. Press A to commit - screen freezes and doesn't update anymore. Device must be rebooted

**Alternate repro:**
1. Boot app as above
2. Press button B to show brightness UI
3. Press button A to dismiss UI - screen freezes with brightness UI still up. Device must be rebooted

**Comment by dclaar** [comment]
You never saw "Wifi connected"?

You see n/a because the web interface doesn't return direct AQI, and I
defaulted to that. I should change the default to one that works in both
places. You can do that yourself to see if you are actually getting to the
internet by switching lines 183 and 184 in
aqi.py.

I will note that Brightness doesn't appear to actually change the
brightness, but it doesn't hang for me. (Both UI bits work for me).

If you can connect to the device--On windows, putty to the serial port
(shows up in Device Manager) with baud=115200 works--you might need to type
control-c a few times, but then you can type "repl" (without quotes), boot
the device, and when it (presumably) crashes, there should be a stack
trace. Or M5Burner has a button to connect. Don't remember its name off the
top of my head.

**Comment by danswett** [comment]
Sorry it wasn't clear - I do see "Wifi connected" followed by "n/a".

If I connect the device and then trigger the error, here's what Putty shows:
Traceback (most recent call last):
  File "main.py", line 48, in <module>
  File "main.py", line 36, in main
  File "aqi.py", line 382, in Run
  File "aqi.py", line 72, in Update
KeyError: name
MicroPython 0f84002d0 on 2020-09-11; M5Stick with ESP32
Type "help()" for more information.
>>>

**Comment by dclaar** [comment]
aqi.json line 72:
< if name in self.defaults and value == self.defaults['name']:
> if name in self.defaults and value == self.defaults[name]:

I didn't catch this because I already had a config file. :(

I'll try to upload a fix tonight, but I'm on-call, so may not get there.

**Comment by danswett** [comment]
No worries! Would manually creating the config file work? I can give that a
shot.
