### ISSUE TITLE
App periodically just stops

### ISSUE THREAD

**Issue by danswett** [dclaar/purple_air#5]
Typically happens after a few hours of uptime, but sometimes faster. The heart will stop drawing and the AQI will stop updating.

Connecting to Putty and doing CTRL+C doesn't show any traceback - it just gives a clean console prompt.

Device is plugged into the USB port on a computer for power, but isn't attached. One device is connected to a mac and one to a PC and both exhibit the same symptom.

**Comment by dclaar** [comment]
Yeah, mine stopped once right after the update, unfortunately not connected
to any computer. I plugged it into a computer, and it has been working
flawlessly since.

Do you have any idea of a common condition that might trigger it? My wild
guess--since mine has not stopped working, and the AQI is *horrible* (well,
OK, not Napa horrible, 181 horrible)--is maybe something about low AQIs.

**Comment by danswett** [comment]
It was happening when the AQI was around 70, and still happening with the 160-170ish we've been getting the past few days. Doesn't seem dependent on the correction - happened with L and N.

I've thought about trying to reflash them to see if that changes anything

**Comment by danswett** [comment]
Seems to be happening much more frequently today (again for whatever reason).

**Comment by dclaar** [comment]
It would be great if you could putty to the device, interrupt with
control-c, and then restart the app on the device. I have 2 running, and I
can't get either to fail. It's really frustrating, because I *know* there's
a bug somewhere! Hopefully I will have time this weekend to try to find it
by code inspection.

**Comment by danswett** [comment]
Sure. So connect Putty, CTRL+C, and then which command to restart it?

**Comment by dclaar** [comment]
Hold down A, press power, go to apps, start app. Just like starting from
scratch.

**Comment by danswett** [comment]
Ah ok. Then presumably CTRL+C when I notice that it's frozen?

**Comment by dclaar** [comment]
Yes, if you don't already see an error.

**Comment by danswett** [comment]
Got it:

Traceback (most recent call last):
  File "main.py", line 48, in <module>
  File "main.py", line 36, in main
  File "aqi.py", line 351, in Run
  File "aqi.py", line 309, in GetData
  File "m5stickc.py", line 237, in GetURI
  File "libs/urequests.py", line 102, in request
NotImplementedError: Redirects not yet supported
MicroPython 0f84002d0 on 2020-09-11; M5Stick with ESP32
Type "help()" for more information.
>>>

**Comment by dclaar** [comment]
Ooh. That's, umm, interesting. That means that purpleair returned a 302
status or similar.

**Comment by dclaar** [comment]
Oh wait, it crashed for me, too! I got a 500 error, which means there's a
problem on their site.

**Comment by dclaar** [comment]
OK, I pushed a hack that will retry after displaying an error message for a while.
Long term fix is to drag in https://github.com/pfalcon/pycopy-lib/tree/master/urequests, which handles redirects.

**Comment by dclaar** [comment]
Added a print statement for the 500 error. Can't do much about the 429. Purple air says they redirect if you hit the site too often, so I've asked what "too often" is.

**Comment by dclaar** [comment]
OK, after chatting with Purple Air, I've upped the interval so that it's not "too often".

**Comment by dclaar** [comment]
Sausage made while you wait. :)

**Comment by danswett** [comment]
👍

**Comment by dclaar** [comment]
I have put more protective code in. I also created my own copy of urequests.py that handles redirection, but it is not yet in the copy scripts. I'm waiting to hear back from Purple Air about how to handle the redirects first.
But I'm closing because even without that, the device should recover after showing a red error screen for 5 seconds.
